# Generated by Django 2.2.1 on 2019-07-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ck_editor', '0003_auto_20190729_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
