# Generated by Django 2.2.1 on 2019-07-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ck_editor', '0004_post_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description2',
        ),
    ]
